version: "3.8"
services:
  api:
    build: ./api
    container_name: docker-demo-api-ctn
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: docker-demo-blog-ctn
    ports:
      - '3000:3000'
    stdin_open: true